name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend
        run: |
          cd backend
          docker build -t roobobo/campus-connect-backend:v3 .
          docker push roobobo/campus-connect-backend:v3

      - name: Build & Push Frontend
        run: |
          cd frontend
          docker build -t roobobo/campus-connect-frontend:v5 .
          docker push roobobo/campus-connect-frontend:v5
